/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.HashMap;

public class App {
    private ArrayList<Pessoa> agenda;

    public App(){
        this.agenda = new ArrayList<>();
    }
    

    public boolean adicionarPessoa(Pessoa p){
        return this.agenda.add(p);
    }

    public boolean removerPessoa(String nome){
        return this.agenda.removeIf(p->p.getNome().equals(nome));
    }

    public void imprimirAgenda(){
        for (Pessoa p: agenda){
            System.out.println(p);
        }
    }


    public static void main(String[] args) {
        App app = new App();
        System.out.println("gustavo e serjão:");
        app.adicionarPessoa(new Pessoa("Gustavo", "emailDoGustavo.email.com"));
        app.adicionarPessoa(new Pessoa("Serjão", "emailDoSerjão.email.com"));

        app.imprimirAgenda();
        app.removerPessoa("Gustavo");
        System.out.println("Removeu o gustavo, agora é pra aparecer só o serjão");
        app.imprimirAgenda();

        // chave, valor
        HashMap<String, Pessoa> contatos = new HashMap<>();

        contatos.put("S", new Pessoa("S", "e"));
        Pessoa a = contatos.get("j");

    }
    


}
