/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {

    public static void main(String[] args) {
        Motor m = new Motor(100);
        Carro fusca = new Carro("fusca", m);

        Carro g = new Carro("gol", null);


        
        
    }
}
