/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import engtelecom.poo.Robos.RoboL3;
import engtelecom.poo.Robos.RoboL5;

public class App {
    public static void main(String[] args) {
        // Variáveis genéricas guardam variáveis específicas


        // Criando duas classes iguais com os mesmos atributos
        RoboL5 a = new RoboL5(null, 1, 2, 3, 'N', 10);
        RoboL5 b = new RoboL5(null, 1, 2, 3, 'N', 10);

        // *****************************************************************************
        // Sempre usar equals pra comparar classes! erro conceitual ao comparar com '=='
        // *****************************************************************************
        if (a.equals(b)){
            System.out.println("iguais");
        } else {
            System.out.println("diferentes");
        }


        
    }
}
