/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

import engtelecom.agenda.Agenda;
import engtelecom.agenda.Email;
import engtelecom.agenda.Pessoa;
import engtelecom.agenda.Telefone;

public class App {
    Agenda agenda = new Agenda();
    Scanner teclado = new Scanner(System.in);

    private void menu(){

        
        int opcao = -1;

        while (opcao != 3){
            System.out.println("..:: Agenda de contatos ::..");
            System.out.println("1 - Cadastrar contato");
            System.out.println("2 - Listar todos os contatos");
            System.out.println("3 - Adicionar informação");
            System.out.println("4 - Excluir contato");
            System.out.println("5 - Sair do programa");
        
            System.out.print("Entre com a opção desejada: ");
            opcao = teclado.nextInt();
        switch(opcao){
            case 1:
                this.cadastrarContato();
                break;
            case 2:
                String lista = agenda.listaDeContatos("");
                System.out.println(lista);
                break;
            case 3:
                this.adicionarInformacao();
            case 4:
                this.excluirContato();
            case 5:
                System.out.println("Tchau");
                break;
            default:
                System.out.println("Opção inválida");
                break;
        }
    }
}

    /**
     * Método de menu interativo que cadastra o contato
     */
    private void cadastrarContato(){

        System.out.println("..::Cadastrar contato..::");
        System.out.println("Nome: ");
        String nome = teclado.next();
        teclado.nextLine();
        System.out.println("Sobrenome: ");
        String sobrenome = teclado.nextLine();
        System.out.println("Data de nascimento (AAAA-MM-DD):: ");
        String dataString = teclado.next();
        teclado.nextLine();
        LocalDate data = LocalDate.parse(dataString);

        Pessoa p = new Pessoa(nome, sobrenome, data);
        agenda.adicionar(p);

        // Verifica se quer adicionar email
        System.out.println("Deseja adicionar um email? (s/n)");
        String opcao = teclado.nextLine();
        if (opcao.equals("s")){
            System.out.println("Endereço de email: ");
            String v = teclado.next();
            teclado.nextLine();
            System.out.println("Digite um rótulo: ");
            String r = teclado.next();
            teclado.nextLine();


            Email e = new Email(r,v);
            if (e.isValido()){
                p.adicionaEmail(r,v);
            } else {
                System.out.println("Email inválido");
            }
        } else {
            // Verifica se quer adicionar telefone
            System.out.println("Deseja adicionar um telefone? (s/n)");
            teclado.next();
            teclado.nextLine();
            if (teclado.equals("s")){
                System.out.println("Digite um rótulo: ");
                String r = teclado.nextLine();
                System.out.println("Digite um número: ");
                String v = teclado.nextLine();
                p.adicionaTelefone(r,v);
            } 
        }
    }    


    /**
     * Método que adiciona informação de email ou telefone ao contato
     */
    private void adicionarInformacao(){
        // Pessoa informa o nome
        System.out.println("Qual o seu nome?");
        String nome = teclado.nextLine();
        //TODO

        // Pergunta se quer adicionar email ou telefone
        System.out.println("O que você deseja adicionar? ");
        System.out.println("1 - Email");
        System.out.println("2 - Telefone");
        int opcao = teclado.nextInt();
        teclado.nextLine();
        if (opcao == 1){
            // adiciona email
            // TODO
        } else if (opcao == 2){
            // adiciona telefone
            // TODO
        } else {
            System.out.println("Insira uma opção válida");
        }
    }

    /**
     * Método para excluir um contato
     * exibe a lista de contatos da agenda
     * e pergunta qual contato o usuário deseja excluir,
     * então exclui o contato solicitado.
     */
    private void excluirContato(){
        String listaContatos = agenda.listaDeContatos("");
        System.out.println(listaContatos);
        System.out.println("Qual contato você deseja excluir? ");
        int op = teclado.nextInt();
        agenda.removePessoa(op);
        }

    


    public static void main(String[] args) {
        App app = new App();
        app.menu();
    }
}