/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Scanner;

import engtelecom.agenda.Agenda;
import engtelecom.agenda.Pessoa;

public class App {
    Agenda agenda = new Agenda();
    Scanner teclado = new Scanner(System.in);

    private void menu(){

        
        int opcao = -1;

        while (opcao != 3){
            System.out.println("..:: Agenda de contatos ::..");
            System.out.println("1 - Cadastrar contato");
            System.out.println("2 - Listar todos os contatos");
            System.out.println("3 - Sair do programa");
        
            System.out.print("Entre com a opção desejada: ");
            opcao = teclado.nextInt();
        switch(opcao){
            case 1:
                this.cadastrarContato();
                break;
            case 2:
                this.listarTodosContatos();
                break;
            case 3:
                System.out.println("Tchau");
                break;
            default:
                System.out.println("Opção inválida");
                break;
        }
    }
}

    private void cadastrarContato(){

        System.out.println("..::Cadastrar contato..::");
        System.out.println("Nome: ");
        String nome = teclado.next();
        teclado.nextLine();
        System.out.println("Sobrenome: ");
        String sobrenome = teclado.nextLine();
        System.out.println("Data de nascimento (AAAA-MM-DD):: ");
        String dataString = teclado.next();
        teclado.nextLine();
        LocalDate data = LocalDate.parse(dataString);

        Pessoa p = new Pessoa(nome, sobrenome, data);
        agenda.adicionar(p);
    }

    private void listarTodosContatos(){
        System.out.println("..:: Contatos ::..");
        agenda.listaDeContatos();
        
    }


    public static void main(String[] args) {

        App app = new App();
        app.menu();


    }
}

