/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

import java.awt.Color;
import java.util.Random;

import javax.swing.text.AttributeSet.ColorAttribute;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;
import edu.princeton.cs.algs4.RandomSeq;

public class App implements DrawListener{
    private Draw desenho;

    /**
     * Construtor da classe onde se inicia um novo objeto Draw
     */
    public App(){
        this.desenho = new Draw();

        this.desenho.addListener(this);
        this.desenho.text(.5,.5,"Olá mundo");
        
    }

    public static void main(String[] args) {
        App aplicativo = new App();

    }

    @Override
    public void mousePressed(double x, double y) {
        this.desenho.text(x,y, "Olá mundo");
                
    }

    @Override
    public void mouseDragged(double x, double y) {
        
    }

    @Override
    public void mouseReleased(double x, double y) {
        
    }

    @Override
    public void mouseClicked(double x, double y) {
        
    }

    @Override
    public void keyTyped(char c) {
        if (c == 'a'){
            this.desenho.text(.1,.1,"Apertou a");
        }

        if (c == 'l'){
            this.limparTela();
        } else {
            this.desenho.text(.7,.7, "Apertou: " + c);
        }
    }

    @Override
    public void keyPressed(int keycode) {
        
    }

    @Override
    public void keyReleased(int keycode) {
        
    }

    public void limparTela(){
        this.desenho.clear(Color.WHITE);
    }
}
