/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;


public class App {

    public static void main(String[] args) {
        Tempo[] exemplos = new Tempo[3];


        exemplos[0] = new Tempo(-5);
        exemplos[1] = new Tempo(5,15);
        exemplos[2] = new Tempo(5,15,30);

        long a = exemplos[2].convertePraSegundos();
        System.out.println("A conversão em segundos é: " + a);


        for (Tempo tempo : exemplos) {
            System.out.println(tempo);
        }





        /*
        Pessoa[] clientes = new Pessoa[10];
        clientes[0] = new Pessoa(1, "789", "João");
        clientes[1] = new Pessoa(2, "123", "Juca");
        clientes[2] = new Pessoa (3, "456", "Ana");
   
        
        for (Pessoa pessoa : clientes) {
            System.out.println("-----------------");
            System.out.println("Id: " + pessoa.getId());
            System.out.println("Nome: " + pessoa.getNome());
            System.out.println("CPF: " + pessoa.getCpf());
        }
        

        for (Pessoa pessoa : clientes) {
            System.out.println("-------------");
            // invoca tostring
            System.out.println(pessoa);
        }
        */
        
    }


}
