/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;


public class App {

    public static void main(String[] args) {
        Tempo exemplo1 = new Tempo(5,15,30);
        Tempo exemplo2 = new Tempo(6,5,10);


        long a = exemplo1.convertePraSegundos();
        long b = exemplo2.convertePraSegundos();
        System.out.println("A conversão em segundos do exemplo 1 é: " + a);
        System.out.println("A conversão em segundos do exemplo 2 é: " + b);
        
        long dif = exemplo1.diferenca(exemplo1, exemplo2);

        System.out.println("A diferença entre A e B é: " + dif);




        /*
        Pessoa[] clientes = new Pessoa[10];
        clientes[0] = new Pessoa(1, "789", "João");
        clientes[1] = new Pessoa(2, "123", "Juca");
        clientes[2] = new Pessoa (3, "456", "Ana");
   
        
        for (Pessoa pessoa : clientes) {
            System.out.println("-----------------");
            System.out.println("Id: " + pessoa.getId());
            System.out.println("Nome: " + pessoa.getNome());
            System.out.println("CPF: " + pessoa.getCpf());
        }
        

        for (Pessoa pessoa : clientes) {
            System.out.println("-------------");
            // invoca tostring
            System.out.println(pessoa);
        }
        */
        
    }


}
