/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

public class App {


    public static void main(String[] args) {
        Carta c = new Carta(Naipe.Ouro, Valor.CINCO);

    }
}
