/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package engtelecom.poo;

/**
 * Minha classe principal
 */
public class App {


    /**
     * Minha classe principal
     * @param args argumentos de linha de comando
     */
    public static void main(String[] args) {
        Calculadora calc = new Calculadora();

    

    
    }
}
